[project]
name = "MD-lab-old"
version = "0.1.0"
description = "Add a short description here"
authors = ["pmitev <pmitev@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
vmd = ">=1.9.3,<1.10"
lammps = ">=2021.9.29,<2021.10"
ase = "3.18.1.*"
ipython = ">=7.33.0,<7.34"
gnuplot = ">=5.4.1,<5.5"
numpy = "1.17.*"
imagemagick = ">=7.1.0_27,<7.1.1"
python = "3.7.*"
