ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config 
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools_deluxe.sh \
                  /ubuntu/install/chrome/install_chrome.sh \
                  /ubuntu/install/firefox/install_firefox.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/ansible/install_ansible.sh \
                  /ubuntu/install/cleanup/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done 

# More packages
RUN apt-get update && apt-get install -y gawk git wget vim less mc \
    build-essential default-jre python3-pip python3-setuptools \
    rootlesskit rpm2cpio cpio bzip2

# Nextflow
RUN cd /usr/bin && wget https://github.com/nextflow-io/nextflow/releases/download/v24.10.5/nextflow-24.10.5-dist && chmod a+rx /usr/bin/nextflow-24.10.5-dist && ln -s nextflow-24.10.5-dist nextflow

# nf-core
RUN python3 -m pip install --no-cache-dir --break-system-packages nf-core

# Apptainer
RUN cd /tmp && wget https://github.com/apptainer/apptainer/releases/download/v1.4.0/apptainer_1.4.0_amd64.deb && apt install -y ./apptainer_1.4.0_amd64.deb && rm apptainer_1.4.0_amd64.deb && apt clean

# miniforge
RUN cd /opt && \
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" && \
    bash Miniforge3-$(uname)-$(uname -m).sh -b -p /opt/miniforge3 && \
    /opt/miniforge3/condabin/conda install conda-build conda-pack && \
    /opt/miniforge3/condabin/conda clean -ay

RUN bash -c 'echo -e "\nsource /opt/miniforge3/etc/profile.d/conda.sh\nsource /opt/miniforge3/etc/profile.d/mamba.sh" >> ${STARTUPDIR}/generate_container_user'

# Finalizing
RUN \
  apt-get clean -y
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME /home/kasm-user
ENV PATH $PATH:/opt/miniforge3/condabin
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
