[project]
name = "MD-lab"
version = "0.1.0"
description = "Add a short description here"
authors = ["pmitev <pmitev@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"
spglib = ">=2.4.0,<2.5"
imagemagick = ">=7.1.1_30,<7.1.2"
vmd = ">=1.9.3,<1.10"
ase = "3.22.1.*"
gnuplot = ">=5.4.8,<5.5"
lammps = ">=2024.2.7,<2024.3"
ipython = ">=8.22.2,<8.23"
